### ISSUE TITLE
Warning about drawBot not installed

### ISSUE THREAD

**Issue by pauldhunt** [thomgb/PDFButtonSpace#1]
I am running Version 1.8.4 (built 1706131209) of Robofont and have installed this extension, but when I launch the Robofont app, I get the following warning:

```
Traceback (most recent call last):
  File "AddButtonPDFToSC.py", line 14, in <module>
ImportError: No module named drawBot
```

Please advise on how to clear this error and get the button to work Properly. Thanks.

**Comment by thomgb** [comment]
Hello Paul,
Thanks for the feedback
I look into this and let you know.

Thom

**Comment by thomgb** [comment]
Hey Paul, remove the drawBot module it was not necessary.
An update via Mechanics should work.
Thanks! Thom

**Comment by pauldhunt** [comment]
Awesome! Thanks for the quick fix. :D

P
