### ISSUE TITLE
2 additional PDF filename options

### ISSUE THREAD

**Issue by LettError** [thomgb/PDFButtonSpace#2]
It would be nice to be a able to include these variables in the PDF filename:
- source UFO filename, for instance by writing `%ufo` in the filename.
- first couple of characters of the text in the spacecenter (perhaps as unicode). For instance by wrinting `%text`

I use this tool a lot when grabbing images (for instance for a presentation) that by nature are not finished fonts (because then I would use the font). Many screenshots in the same folder...

**Comment by thomgb** [comment]
I've added them.

**Comment by thomgb** [comment]
Seems that `os.system("open '%s'" % filename)` is erroring if weird characters are in the filename. The semi-solve is that if weird characters then instead of opening the pdf it does a show-in-finder thing

**Comment by LettError** [comment]
Maybe try `os.system(u"open '%s'" % filename)`

**Comment by thomgb** [comment]
That was my idea too when if start erroring. But it is not a solve :(

**Comment by thomgb** [comment]
In Terminal this works but in RF not...

**Comment by LettError** [comment]
Also I think you need to filter on "/" when including glyphnames in the filename. (which is not unusual)

**Comment by thomgb** [comment]
✔︎
